[package]
name = "monregister"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
#tokio = { version = "1.42.0", features = ["full"] }
#lettre = "0.11.11"
colored = "2.0.1"
crossterm = "0.28.1"
notify-rust = "4.11.3"
