[package]
name = "bot"
version = "0.1.0"
edition = "2021"


[dependencies]

serenity = "0.12.0"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
rand = "0.8.5"
