[package]
name = "rusty_tasker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ['derive'] }
serde_json = "1.0.108"

chrono = "0.4.31"
prettytable = "0.10.0"
colored = "2.1.0"
